[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=59.6.0", "wheel"]

[tool.black]
line-length = 100
target-version = ["py36"]

[tool.isort]
line_length = 100
profile = "black"

[tool.pytest.ini_options]
addopts = ["-l", "-v"]
testpaths = ["tests"]
